package com.prama.recyclerviewapp;

class MyItem {

    static int[] iconList = {
            R.drawable.facebook,
            R.drawable.twitter,
            R.drawable.instagram,
            R.drawable.snapchat,
            R.drawable.whatsapp,
            R.drawable.line,
            R.drawable.kakaotalk,
            R.drawable.telegram,
            R.drawable.messenger,
            R.drawable.youtube,
            R.drawable.tiktok,
            R.drawable.vine,
            R.drawable.vimeo,
            R.drawable.figma,
            R.drawable.adobe_xd,
            R.drawable.sketch,
            R.drawable.framer,
            R.drawable.android,
            R.drawable.apple,
            R.drawable.windows,
            R.drawable.opera,
            R.drawable.firefox,
            R.drawable.safari,
            R.drawable.edge,
            R.drawable.paypal,
            R.drawable.mastercard,
            R.drawable.visa,
            R.drawable.bitcoin,
            R.drawable.ethereum
    };

    static String[] Headline = {
            "Facebook",
            "Twitter",
            "Instagram",
            "SnapChat",
            "WhatsApp",
            "LINE",
            "KakaoTalk",
            "Telegram",
            "Messenger",
            "YouTube",
            "TikTok",
            "Vine",
            "Vimeo",
            "Figma",
            "Adobe XD",
            "Sketch",
            "Framer",
            "Android",
            "iOS",
            "Windows",
            "Opera",
            "Mozilla",
            "Safari",
            "Edge",
            "Paypal",
            "Mastercard",
            "Visa",
            "Bitcoin",
            "Ethereum"
    };

    static String[] Subhead = {
            "Meta Platforms, Inc., disingkat sebagai Meta dan sebelumnya dikenal juga sebagai Facebook, Inc. hingga 28 Oktober 2021, adalah sebuah layanan jejaring sosial berkantor pusat di Menlo Park, California, Amerika Serikat yang diluncurkan pada bulan Februari 2004.",
            "Twitter adalah layanan jejaring sosial dan mikroblog daring yang memungkinkan penggunanya untuk mengirim dan membaca pesan berbasis teks hingga 140 karakter akan tetapi pada tanggal 07 November 2017 bertambah hingga 280 karakter yang dikenal dengan sebutan kicauan.",
            "Instagram adalah sebuah aplikasi berbagi foto dan video yang memungkinkan pengguna mengambil foto, mengambil video, menerapkan filter digital, dan membagikannya ke berbagai layanan jejaring sosial, termasuk milik Instagram sendiri.",
            "Snapchat adalah aplikasi pesan foto yang dikembangkan Evan Spiegel, Bobby Murphy, dan Reggie Brown saat masih kuliah di Universitas Stanford. Dengan aplikasi ini, pengguna dapat mengambil foto, merekam video, menambahkan teks dan lukisan, dan mengirimkannya ke daftar penerima yang ditentukan pengguna.",
            "WhatsApp Messenger adalah aplikasi pesan untuk ponsel cerdas. WhatsApp Messenger merupakan aplikasi pesan lintas platform yang memungkinkan kita bertukar pesan tanpa pulsa, karena WhatsApp Messenger menggunakan paket data internet.",
            "Line adalah aplikasi pengirim pesan instan gratis yang dapat digunakan pada berbagai perangkat elektronik, seperti telepon cerdas, tablet, dan komputer. Pengguna Line bertukar teks, gambar, video dan audio, dan melakukan percakapan VoIP dan konferensi video gratis.",
            "KakaoTalk adalah sebuah aplikasi messenger lintas platform yang tersedia bagi pengguna smartphone. KakaoTalk memungkinkan penggunanya untuk mengirim pesan tanpa membayar karena ia menggunakan jaringan internet untuk mengirimkan pesan tersebut.",
            "Telegram adalah sebuah aplikasi layanan pengirim pesan instan multiplatform berbasis awan yang bersifat gratis dan nirlaba. Klien Telegram tersedia untuk perangkat telepon seluler dan sistem perangkat komputer. Para pengguna dapat mengirim pesan dan bertukar foto, video, stiker, audio, dan tipe berkas lainnya.",
            "Messenger adalah sebuah situs aplikasi perangkat lunak yang digunakan untuk instant messaging yang mempermudah pengguna facebook dalam berkomunikasi satu sama lain melalui pesan teks, panggilan suara dan kini terdapat panggilan video.",
            "YouTube adalah sebuah situs web berbagi video yang dibuat oleh tiga mantan karyawan PayPal pada Februari 2005. Situs web ini memungkinkan pengguna mengunggah, menonton, dan berbagi video.",
            "TikTok adalah sebuah jaringan sosial dan platform video musik Tiongkok yang dluncurkan pada September 2016 oleh Zhang Yiming, pendiri Toutiao. Aplikasi tersebut membolehkan para pemakai untuk membuat video musik pendek mereka sendiri.",
            "Vine adalah aplikasi layanan berbagi video berdurasi pendek. Dibuat pada Juni 2012 dan diakuisisi oleh Twitter pada Oktober 2012.",
            "Vimeo adalah situs layanan berbagi video yang memungkinkan penggunanya untuk mengunggah, berbagi, dan menonton video. Vimeo diciptakan oleh Jake Lodwick dan Zach Klein pada November 2004.",
            "Figma adalah editor grafik vektor dan alat prototyping yang terutama berbasis web, dengan fitur offline tambahan yang diaktifkan oleh aplikasi desktop untuk macOS dan Windows.",
            "Adobe XD adalah alat desain pengalaman pengguna berbasis vektor untuk aplikasi web dan aplikasi seluler, dikembangkan dan diterbitkan oleh Adobe Inc. Ini tersedia untuk macOS dan Windows, meskipun ada versi untuk iOS dan Android untuk membantu melihat pratinjau hasil pekerjaan secara langsung di perangkat seluler.",
            "Sketch adalah editor grafis vektor untuk macOS yang dikembangkan oleh perusahaan Belanda Sketch B.V. Ini pertama kali dirilis pada 7 September 2010 dan memenangkan Penghargaan Desain Apple pada 2012. Ini juga memiliki aplikasi web yang memungkinkan pengguna untuk menggunakan platform di komputer mana pun.",
            "Framer adalah salah satu alat prototyping paling populer. Ini didasarkan pada premis bahwa dengan kode itu adalah mungkin untuk membuat prototipe apa pun, menghasilkan novel dan desain yang indah.",
            "Android adalah sistem operasi berbasis Linux yang dirancang untuk perangkat bergerak layar sentuh seperti telepon pintar dan komputer tablet. Android awalnya dikembangkan oleh Android, Inc., dengan dukungan finansial dari Google, yang kemudian membelinya pada tahun 2005.",
            "iOS (sebelumnya iPhone OS) adalah sistem operasi seluler yang dibuat dan dikembangkan oleh Apple Inc. khusus untuk perangkat kerasnya. Ini adalah sistem operasi yang saat ini memberdayakan banyak perangkat seluler perusahaan, termasuk iPhone, dan iPod Touch; itu juga mendukung iPad sebelum pengenalan iPadOS pada 2019. Ini adalah sistem operasi seluler terpopuler kedua di dunia setelah Android.",
            "Microsoft Windows atau yang lebih dikenal dengan sebutan Windows saja adalah keluarga sistem operasi yang dikembangkan oleh Microsoft, dengan menggunakan antarmuka pengguna grafis. Sistem operasi Windows telah berevolusi dari MS-DOS, sebuah sistem operasi yang berbasis modus teks dan command-line.",
            "Opera adalah peramban web dan paket perangkat lunak Internet antar-platform. Opera terdiri dari kumpulan perangkat lunak untuk Internet seperti peramban web, serta perangkat lunak untuk membaca dan mengirim surat elektronik. Opera dibuat oleh Opera Software yang bermarkas di Oslo, Norwegia.",
            "Mozilla Firefox, atau Firefox adalah peramban web lintas platform bebas dan sumber terbuka yang dikembangkan oleh Yayasan Mozilla dan ratusan sukarelawan.",
            "Safari adalah sebuah peramban web buatan Apple Inc. yang awalnya ditujukan khusus bagi sistem operasi Mac OS. Safari dipasang bersama Mac OS X dan merupakan peramban web bawaan di sistem operasi tersebut sejak Mac OS X v10.3.",
            "Microsoft Edge, awalnya dikembangkan di bawah nama kode Project Spartan, adalah peramban web yang dikembangkan oleh Microsoft dan termasuk dalam sistem operasi Windows. Resmi dirilis pada tanggal 29 Juli 2015, peramban ini menggantikan Internet Explorer sebagai peramban baku pada Windows 10.",
            "PayPal adalah perusahaan penyedia layanan elektronik yang memfasilitasi pembayaran antar pihak melalui transfer online. PayPal memungkinkan pelanggan untuk membuat akun di platformnya, yang terhubung ke kartu kredit atau rekening giro pengguna.",
            "MasterCard Worldwide merupakan organisasi keanggotaan yang dimiliki oleh lebih dari 25.000 institusi keuangan yang menerbitkan kartunya. MasterCard adalah merek dari kartu kredit yang diterbitkan perusahaan tersebut.",
            "Visa Inc. adalah perusahaan jasa keuangan multinasional Amerika yang berkantor pusat di Foster City, California, Amerika Serikat. Perusahaan ini memfasilitasi transfer dana elektronik di seluruh dunia, umumnya melalui kartu kredit, kartu hadiah, dan kartu debit berlogo-Visa.",
            "Bitcoin adalah sebuah uang elektronik yang dibuat pada tahun 2009 oleh Satoshi Nakamoto. Nama tersebut juga dikaitkan dengan perangkat lunak sumber terbuka yang dia rancang, dan juga menggunakan jaringan",
            "Ethereum adalah sebuah platform rantai-blok dengan fungsi kontrak cerdas. Ethereum mempunyai fungsi seumpama virtual machine yang bisa menjalankan kontrak cerdas peer-to-peer dengan uang kripto Ether. Ethereum merupakan sebuah projek besar yang dimulai oleh Vitalik Buterin pada tahun 2013."
    };
}
